import type { Meta, StoryObj } from '@storybook/react-vite';
import { ComboBox } from './ComboBox';
const people = ['Alex Morgan', 'Priya Raman', 'Jonas Weber', 'Mia Castillo', 'Tom Okafor', 'Sara Lind', 'Daniel Reyes', 'Nora Bennett', 'Ivan Petrov', 'Grace Mwangi', 'Leo Fontaine', 'Hana Suzuki'].map((n, i) => ({ id: String(i), label: n, description: ['Engineering', 'Sales', 'Operations'][i % 3] }));
const meta: Meta<typeof ComboBox> = { title: 'Components/ComboBox', component: ComboBox, tags: ['autodocs'], args: { label: 'Assign to', options: people, placeholder: 'Type a name…' }, argTypes: { options: { control: false }, size: { control: 'radio', options: ['sm', 'md', 'lg'] } }, decorators: [(S) => <div style={{ width: 320 }}><S /></div>] };
export default meta;
type Story = StoryObj<typeof ComboBox>;
export const Default: Story = {};
export const Selected: Story = { args: { defaultSelected: '4' } };
export const Error: Story = { args: { error: 'Pick someone from the list.' } };
export const Disabled: Story = { args: { disabled: true, defaultSelected: '1' } };
