import type { Meta, StoryObj } from '@storybook/react-vite';
import { Select } from './Select';
const roles = [{ value: 'admin', label: 'Administrator' }, { value: 'editor', label: 'Editor' }, { value: 'viewer', label: 'Viewer' }, { value: 'guest', label: 'Guest (expired)', disabled: true }];
const meta: Meta<typeof Select> = { title: 'Components/Select', component: Select, tags: ['autodocs'], args: { label: 'Role', options: roles, size: 'md' }, argTypes: { size: { control: 'radio', options: ['sm', 'md', 'lg'] }, options: { control: false } }, decorators: [(S) => <div style={{ width: 320 }}><S /></div>] };
export default meta;
type Story = StoryObj<typeof Select>;
export const Default: Story = {};
export const Selected: Story = { args: { defaultValue: 'editor' } };
export const WithHint: Story = { args: { hint: 'You can change this later in member settings.' } };
export const Error: Story = { args: { error: 'Pick a role to continue.' } };
export const Disabled: Story = { args: { disabled: true, defaultValue: 'viewer' } };
