import type { Meta, StoryObj } from '@storybook/react-vite';
import { Checkbox } from './Checkbox';
const meta: Meta<typeof Checkbox> = { title: 'Components/Checkbox', component: Checkbox, tags: ['autodocs'], args: { label: 'Send email notifications' } };
export default meta;
type Story = StoryObj<typeof Checkbox>;
export const Default: Story = {};
export const Checked: Story = { args: { defaultChecked: true } };
export const WithDescription: Story = { args: { description: 'You will get at most one email a day.' } };
export const Disabled: Story = { args: { disabled: true } };
export const DisabledChecked: Story = { args: { disabled: true, defaultChecked: true } };
