import type { Meta, StoryObj } from '@storybook/react-vite';
import { EmptyState } from './EmptyState';
import { Button } from '../Button/Button';
const Icon = () => <svg viewBox="0 0 48 48" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="20" cy="18" r="7" /><path d="M8 40c0-7 5-11 12-11s12 4 12 11M32 16h10M37 11v10" /></svg>;
const meta: Meta<typeof EmptyState> = { title: 'Components/EmptyState', component: EmptyState, tags: ['autodocs'], argTypes: { icon: { control: false }, action: { control: false }, size: { control: 'radio', options: ['default', 'compact'] } }, decorators: [(S) => <div style={{ width: 480, border: '1px dashed var(--color-border-default)', borderRadius: 12 }}><S /></div>] };
export default meta;
type Story = StoryObj<typeof EmptyState>;
export const FirstTime: Story = { args: { title: 'No members yet', description: 'Invite a colleague to start working together.', icon: <Icon />, action: <Button>Invite member</Button> } };
export const NoResults: Story = { args: { title: 'No results for "morgan lee"', description: 'Try a shorter name, or clear the filters.', action: <Button variant="secondary">Clear filters</Button> } };
export const LoadError: Story = { args: { title: 'Couldn\u2019t load the list', description: 'Check your connection, then try again.', action: <Button variant="secondary">Try again</Button>, size: 'compact' } };
